spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foodbridge_dev
    username: foodbridge_admin
    password: securepassword123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: root
      password: root